export type PositionView = {
  stockMint?: string;
  address: string;
  owner: string;
  manifest: string;
  principalBasis: string;
  shares: string;
  claimable: string;
  grossYield: string;
  yieldFees: string;
  allocatedYield: string;
  kind: Record<string, object>;
  destination: Record<string, object>;
  status: Record<string, object>;
  autoPacks: boolean;
  stockIndex: number;
  stockUnitsReceived: string;
  stockUsdcSpent: string;
  targetPrice: string;
  stepsRemaining: number;
  nextFillAt: string;
  expiresAt: string;
};
export type BatchView = {
  address: string;
  owner: string;
  manifest: string;
  remaining: string;
  nextOpen: string;
  unitFee: string;
  source: Record<string, object>;
  message: string;
  sender: string;
};
export type PackView = {
  lucky?: boolean;
  round?: number;
  stake?: string;
  budget?: string;
  stockMint?: string;
  displayUnits?: string;
  address: string;
  owner: string;
  manifest: string;
  stockIndex: number;
  status: Record<string, object>;
  source: Record<string, object>;
  unitsReceived: string;
  stockValue: string;
  expiresAt: string;
};
export type ProtocolView = {
  packExecution?: { enabled: boolean; authority: string; maxBudget: string };
  luckyPool?: {
    enabled: boolean;
    reserve: string;
    maxStake: string;
    address: string;
  };
  available: boolean;
  paused: boolean;
  error?: string;
  programId: string;
  vault: string;
  yieldShareBps: number;
  packFeeBps: number;
  tradeFeeBps: number;
  apy: number | null;
  tvl: string | null;
  positions: PositionView[];
  batches: BatchView[];
  packs: PackView[];
  stocks: { mint: string; decimals: number; packEligible: boolean }[];
  summary: {
    principal: string;
    grossYield: string;
    yieldFees: string;
    claimable: string;
    sealed: string;
    activeOrders: number;
  };
  observedAt: string;
};
export type PreparedAction = {
  transaction: string;
  blockhash: string;
  lastValidBlockHeight: number;
  resource: string;
  review: Record<string, string | number | boolean>;
};
