/**
 * Verified pool registry: load, index and validate `src/data/router/pools.json`.
 *
 * The file is generated by `scripts/router/build-pool-registry.ts` from the
 * discovery dumps. This module never fetches; it only reads the committed
 * file, so a runtime quote can never be routed to a pool nobody reviewed.
 *
 * Two invariants are enforced at load time and again in `poolsForRepresentation`:
 *  - every pool pairs a registry mint with USDC, exactly, in either order;
 *  - a pool is only usable when `enabled` is true.
 */
import pools from "@/data/router/pools.json";
import { isQualifiedIntermediate } from "./intermediates";
import { USDC_MINT, type VerifiedPool, type Venue } from "./types";

const BASE58 = /^[1-9A-HJ-NP-Za-km-z]{32,44}$/;

export type PoolRegistry = {
  pools: VerifiedPool[];
  byRepresentation: Map<string, VerifiedPool[]>;
  byAddress: Map<string, VerifiedPool>;
};

export function validatePool(pool: VerifiedPool) {
  const problems: string[] = [];
  if (!BASE58.test(pool.address)) problems.push("address is not base58");
  if (!BASE58.test(pool.programId)) problems.push("programId is not base58");
  if (!BASE58.test(pool.mint)) problems.push("mint is not base58");
  const pair = new Set([pool.baseMint, pool.quoteMint]);
  if (pair.size !== 2) problems.push("base and quote mint are identical");
  if (!pair.has(pool.mint)) problems.push("pool does not contain its own mint");
  if (pool.mint === USDC_MINT) problems.push("representation mint is USDC");
  // Eligibility is derived from the pair, never declared freely: a record
  // may only call itself ROUTER_ELIGIBLE if it is exactly {mint, USDC}.
  const usdcPair = pair.has(USDC_MINT);
  const routingAsset = [...pair].find((m) => m !== pool.mint && isQualifiedIntermediate(m)) ?? null;
  if (pool.eligibility === "ROUTER_ELIGIBLE" && !usdcPair)
    problems.push("ROUTER_ELIGIBLE pool does not pair with USDC");
  /* A routing leg pairs the representation with an approved intermediate and
     nothing else. Anything paired with USDC is a direct route, and anything
     paired with an asset outside the intermediate universe is infrastructure:
     calling either a routing leg would put an unapproved asset in the middle
     of an automatic route. */
  if (pool.eligibility === "ROUTING_LEG" && usdcPair)
    problems.push("USDC-paired pool is a direct route, not a routing leg");
  if (pool.eligibility === "ROUTING_LEG" && !routingAsset)
    problems.push("ROUTING_LEG pool does not pair with a qualified intermediate");
  if (pool.eligibility === "STOCK_PAIRED_INFRASTRUCTURE" && usdcPair)
    problems.push("USDC-paired pool must be ROUTER_ELIGIBLE, not infrastructure");
  if (pool.eligibility === "STOCK_PAIRED_INFRASTRUCTURE" && pool.enabled)
    problems.push("STOCK_PAIRED_INFRASTRUCTURE pool cannot be enabled for routing");
  if (pool.poolType === "dbc" && !pool.dbc) problems.push("dbc pool without dbc record");
  if (pool.poolType !== "dbc" && pool.dbc) problems.push("non-dbc pool carries a dbc record");
  if (pool.dbc) {
    if (!BASE58.test(pool.dbc.configAddress)) problems.push("dbc.configAddress is not base58");
    if (pool.dbc.successorStatus === "CONFIRMED" && !pool.dbc.successorPoolAddress)
      problems.push("dbc successor CONFIRMED without successorPoolAddress");
    if (pool.dbc.successorStatus !== "CONFIRMED" && pool.dbc.successorPoolAddress)
      problems.push(`dbc successor ${pool.dbc.successorStatus} carries successorPoolAddress`);
    if (pool.dbc.lifecycle === "GRADUATED" && pool.dbc.successorStatus === "NOT_APPLICABLE")
      problems.push("GRADUATED dbc pool must resolve a successor (CONFIRMED or UNRESOLVED)");
    if (pool.dbc.lifecycle !== "BONDING" && pool.enabled)
      problems.push(`dbc pool in ${pool.dbc.lifecycle} cannot be enabled for routing`);
  }
  if (pool.enabled && pool.disabledReason)
    problems.push("enabled pool carries a disabledReason");
  if (!pool.enabled && !pool.disabledReason)
    problems.push("disabled pool has no disabledReason");
  if (!pool.verifiedAt) problems.push("missing verifiedAt");
  // Verification state and its timestamp must agree, so a DISCOVERED pool
  // can never read as chain-verified by carrying a stray timestamp.
  if (pool.verification === "ONCHAIN_VERIFIED" && !pool.onchainVerifiedAt)
    problems.push("ONCHAIN_VERIFIED without onchainVerifiedAt");
  if (pool.verification !== "ONCHAIN_VERIFIED" && pool.onchainVerifiedAt)
    problems.push(`${pool.verification} pool carries onchainVerifiedAt`);
  if (pool.verification === "VERIFICATION_FAILED" && pool.enabled)
    problems.push("VERIFICATION_FAILED pool is enabled");
  if (pool.verification === "VERIFICATION_FAILED" && !pool.verificationDetail)
    problems.push("VERIFICATION_FAILED without verificationDetail");
  return problems;
}

export function buildPoolRegistry(entries: VerifiedPool[]): PoolRegistry {
  const byRepresentation = new Map<string, VerifiedPool[]>();
  const byAddress = new Map<string, VerifiedPool>();
  for (const pool of entries) {
    const problems = validatePool(pool);
    if (problems.length)
      throw new Error(
        `Invalid pool ${pool.address}: ${problems.join("; ")}`,
      );
    if (byAddress.has(pool.address))
      throw new Error(`Duplicate pool address ${pool.address}`);
    byAddress.set(pool.address, pool);
    const list = byRepresentation.get(pool.representationId) ?? [];
    list.push(pool);
    byRepresentation.set(pool.representationId, list);
  }
  return { pools: entries, byRepresentation, byAddress };
}

let cached: PoolRegistry | null = null;

export function loadPoolRegistry(): PoolRegistry {
  if (!cached) cached = buildPoolRegistry(pools as VerifiedPool[]);
  return cached;
}

/**
 * Pools that trade exactly this pair, in either order.
 *
 * Selection used to be "the deepest enabled pool for this representation",
 * which was safe only while every pool was a USDC pair. With routing legs
 * admitted, the deepest pool for a representation can be its SOL pool, and
 * offering that for a USDC request would lose the quote entirely. A pool is
 * now only ever offered for the pair it actually trades.
 */
export function poolsForPair(
  mintA: string,
  mintB: string,
  options?: { includeDisabled?: boolean; registry?: PoolRegistry },
) {
  const registry = options?.registry ?? loadPoolRegistry();
  const wanted = new Set([mintA, mintB]);
  if (wanted.size !== 2) return [];
  return registry.pools.filter(
    (pool) =>
      (options?.includeDisabled || pool.enabled) &&
      wanted.has(pool.baseMint) &&
      wanted.has(pool.quoteMint),
  );
}

export function poolsForRepresentation(
  representationId: string,
  options?: { venue?: Venue; includeDisabled?: boolean; registry?: PoolRegistry },
): VerifiedPool[] {
  const registry = options?.registry ?? loadPoolRegistry();
  const all = registry.byRepresentation.get(representationId) ?? [];
  return all.filter(
    (pool) =>
      (options?.includeDisabled || pool.enabled) &&
      (!options?.venue || pool.venue === options.venue),
  );
}

export function poolByAddress(address: string, registry?: PoolRegistry) {
  return (registry ?? loadPoolRegistry()).byAddress.get(address) ?? null;
}

/**
 * Stock-paired markets Henar indexes and monitors but never routes. These
 * never reach `poolsForRepresentation` because they are never enabled; this
 * is the only accessor for them.
 */
export function listInfrastructurePools(
  options?: { venue?: Venue; representationId?: string; registry?: PoolRegistry },
) {
  const registry = options?.registry ?? loadPoolRegistry();
  return registry.pools.filter(
    (pool) =>
      pool.eligibility === "STOCK_PAIRED_INFRASTRUCTURE" &&
      (!options?.venue || pool.venue === options.venue) &&
      (!options?.representationId || pool.representationId === options.representationId),
  );
}

/** Every DBC record, eligible or not, for lifecycle refresh and monitoring. */
export function listDbcPools(registry?: PoolRegistry) {
  return (registry ?? loadPoolRegistry()).pools.filter((pool) => pool.poolType === "dbc");
}
