create table if not exists public.company_research_cache (
  ticker text not null check (ticker ~ '^[A-Z0-9.\-]{1,16}$'),
  section text not null check (
    section in ('profile', 'financials', 'earnings', 'dividends', 'filings')
  ),
  payload jsonb not null,
  source_url text not null check (source_url like 'https://%'),
  source_as_of timestamptz,
  fetched_at timestamptz not null default now(),
  expires_at timestamptz not null,
  primary key (ticker, section)
);

create index if not exists company_research_cache_expiry_idx
  on public.company_research_cache (expires_at);

alter table public.company_research_cache enable row level security;
revoke all on public.company_research_cache from anon, authenticated;

create table if not exists public.company_news (
  id bigint generated by default as identity primary key,
  ticker text not null check (ticker ~ '^[A-Z0-9.\-]{1,16}$'),
  headline text not null check (char_length(headline) between 1 and 500),
  publisher text not null check (char_length(publisher) between 1 and 160),
  article_url text not null check (article_url like 'https://%'),
  published_at timestamptz not null,
  source_feed text not null default 'gdelt',
  ingested_at timestamptz not null default now(),
  unique (ticker, article_url)
);

create index if not exists company_news_ticker_published_idx
  on public.company_news (ticker, published_at desc);

alter table public.company_news enable row level security;
revoke all on public.company_news from anon, authenticated;

create table if not exists public.market_data_runs (
  id bigint generated by default as identity primary key,
  source text not null,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  status text not null check (status in ('running', 'complete', 'failed')),
  rows_written integer not null default 0 check (rows_written >= 0),
  error text
);

create index if not exists market_data_runs_source_started_idx
  on public.market_data_runs (source, started_at desc);

alter table public.market_data_runs enable row level security;
revoke all on public.market_data_runs from anon, authenticated;

comment on table public.company_research_cache is
  'Server-maintained cache of sourced issuer research. Never authoritative for balances, ownership, or execution.';
comment on table public.company_news is
  'Deduplicated article metadata. Article content remains at the publisher URL.';
